name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Build Project"]
    types:
      - completed

jobs:
  publish-to-testpypi:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: dev
      url: https://test.pypi.org/p/llm_foundation

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      id: download-artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: build.yaml
        workflow_conclusion: success      
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
